name: "Vehicle  Simulator CI by Zia <github.com/ziaagikian>"
author: 'Zia Ur Rahman <githu.com/ziaagikian>'
 #Default  Xenial has JDK issues
dist: trusty 
language: java
jdk:
  - openjdk8

before_cache:
  - rm -f  ./gradle/caches/modules-2/modules-2.lock
  - rm -rf ./gradle/caches/*/plugin-resolution/
cache:
  directories:
    - ./gradle/caches
    - ./gradle/wrapper

#Build only master and git Tags [v1.0]
branches:
  only:
    - master
    - /v\d+\.\d+/

stages:
  - unit-test
  - build
  - release

jobs:
  include:
    - stage : unit-test
      name : "Vehicle Simulator Unit Test Automation"
      script:
      # Run unit test
        - ./gradlew test
    
    - stage: build
      name: "Gradle and Docker build artifacts"
      script:
        # Build for Java
        - ./gradlew build
        # Build Docker Image
        - ./gradlew dockerBuildImage
      
    - stage: release
      name: "Github Release"
      script: echo "Deploying to GitHub releases ..."

      # Github  Release  Managment Settings
      before_deploy:
        # - export TRAVIS_TAG=$GIT_TAG
        # - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
        - git config --local user.name "$GITHUB_USER_NAME"
        - git config --local user.email "$GITHUB_USER_EMAIL"
        # - git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"

      deploy:
        provider: releases
        api_key: $GITHUB_API_KEY
        file: $TRAVIS_BUILD_DIR/build/libs/VehicleSimulator-1.0.0.jar
        skip_cleanup: true
        name: release-build-$TRAVIS_COMMIT
        body: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
        prerelease: true
        overwrite: true
        target_commitish: $TRAVIS_COMMIT
        on:
          # tags: true
          repo: ziaagikian/Vehicle-Simulator
          all_branches: true

      after_deploy:
        - rm -rf $TRAVIS_BUILD_DIR/build/

after_success:
  echo "Build Succesfull"

after_failure:
  echo "Build Unsuccesfull"

#Send success Failure notifications for master branch only
notifications:
  email: 
    recipients:
      - $GITHUB_USER_EMAIL
    on_success: never
    on_failure: always
